// Miras Oyunu - Precompiled Market Data (May 2025 - May 2026)
// Generated by scripts/compile_market_data.js on 2026-05-24T07:58:27.769Z

const TICKER_INFO = {
  "THYAO": {
    "name": "Türk Hava Yolları",
    "base": 293.53,
    "vol": 0.012,
    "currency": "TRY"
  },
  "EREGL": {
    "name": "Ereğli Demir Çelik",
    "base": 51.5,
    "vol": 0.01,
    "currency": "TRY"
  },
  "ASELS": {
    "name": "Aselsan Elektronik",
    "base": 55.66,
    "vol": 0.016,
    "currency": "TRY"
  },
  "GUBRF": {
    "name": "Gübre Fabrikaları",
    "base": 169.27,
    "vol": 0.045,
    "currency": "TRY"
  },
  "KCHOL": {
    "name": "Koç Holding",
    "base": 181.69,
    "vol": 0.012,
    "currency": "TRY"
  },
  "TUPRS": {
    "name": "Tüpraş Rafinerileri",
    "base": 160.46,
    "vol": 0.014,
    "currency": "TRY"
  },
  "YKBNK": {
    "name": "Yapı Kredi Bankası",
    "base": 28.43,
    "vol": 0.018,
    "currency": "TRY"
  },
  "BIMAS": {
    "name": "BİM Birleşik Mağazalar",
    "base": 381.95,
    "vol": 0.009,
    "currency": "TRY"
  },
  "SASA": {
    "name": "Sasa Polyester",
    "base": 44.93,
    "vol": 0.022,
    "currency": "TRY"
  },
  "ALTIN": {
    "name": "Gram Altın (Banka)",
    "base": 2391.83,
    "vol": 0.006,
    "currency": "TRY"
  },
  "BTC": {
    "name": "Bitcoin",
    "base": 62673.17,
    "vol": 0.02,
    "currency": "USD"
  },
  "ETH": {
    "name": "Ethereum",
    "base": 3097.91,
    "vol": 0.025,
    "currency": "USD"
  },
  "SOL": {
    "name": "Solana",
    "base": 145.12,
    "vol": 0.035,
    "currency": "USD"
  },
  "EUROBOND": {
    "name": "Hazine Dolar Tahvili",
    "base": 1000,
    "vol": 0,
    "currency": "USD"
  }
};

const MACRO_DATABASE = [
  {
    "usdTry": 32.2293,
    "tcmbRate": 37,
    "kfeIndex": 1.0012,
    "stockPrices": {
      "THYAO": 293.53,
      "EREGL": 51.5,
      "ASELS": 55.66,
      "GUBRF": 169.27,
      "KCHOL": 181.69,
      "TUPRS": 160.46,
      "YKBNK": 28.43,
      "BIMAS": 381.95,
      "SASA": 44.93,
      "ALTIN": 2391.83,
      "BTC": 62673.17,
      "ETH": 3097.91,
      "SOL": 145.12,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Miras Vasiyeti Sulh Hukuk'tan Onaylandı!",
      "body": "Büyük amcanızdan kalan 1.000.000 USD tutarındaki miras tescil edildi. Türkiye'nin dalgalı kurları ve enflasyonu altında parayı 365 gün eritmeden işletmelisiniz!"
    }
  },
  {
    "usdTry": 32.2972,
    "tcmbRate": 37,
    "kfeIndex": 1.0041,
    "stockPrices": {
      "THYAO": 301.54,
      "EREGL": 51.43,
      "ASELS": 57.13,
      "GUBRF": 188.72,
      "KCHOL": 185.55,
      "TUPRS": 161.53,
      "YKBNK": 29.37,
      "BIMAS": 386.45,
      "SASA": 44.65,
      "ALTIN": 2416.63,
      "BTC": 64214.14,
      "ETH": 3316.63,
      "SOL": 156.16,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Kuyumcularda Çeyrek Altın Kuyruğu",
      "body": "Dolar kuru dalgalanırken vatandaşlar birikimlerini korumak için kuyumculara koştu. Çeyrek altın tedariğinde sıkıntı yaşanıyor."
    }
  },
  {
    "usdTry": 32.3648,
    "tcmbRate": 37,
    "kfeIndex": 1.007,
    "stockPrices": {
      "THYAO": 308.87,
      "EREGL": 51.26,
      "ASELS": 58.46,
      "GUBRF": 201.67,
      "KCHOL": 189.23,
      "TUPRS": 162.58,
      "YKBNK": 30.15,
      "BIMAS": 390.82,
      "SASA": 44.21,
      "ALTIN": 2440.93,
      "BTC": 65553.11,
      "ETH": 3507.33,
      "SOL": 164.74,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Altında Gramaj Tartışması Gündemde",
      "body": "Kuyumcular Derneği çeyrek altının yarısı büyüklüğünde 'mini çeyrek' basımı önerdi. Düğün sahipleri kararı bekliyor."
    }
  },
  {
    "usdTry": 32.4317,
    "tcmbRate": 37,
    "kfeIndex": 1.0099,
    "stockPrices": {
      "THYAO": 315.07,
      "EREGL": 50.97,
      "ASELS": 59.55,
      "GUBRF": 205.19,
      "KCHOL": 192.57,
      "TUPRS": 163.6,
      "YKBNK": 30.68,
      "BIMAS": 394.98,
      "SASA": 43.63,
      "ALTIN": 2464.2,
      "BTC": 66524.02,
      "ETH": 3652.44,
      "SOL": 169.55,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "BIST Hisselerinde Düzeltme Hareketi",
      "body": "Son haftalardaki hızlı yükseliş sonrası endekste kar realizasyonu başladı. Panik yapan küçük yatırımcı hisse satıyor."
    }
  },
  {
    "usdTry": 32.4979,
    "tcmbRate": 37,
    "kfeIndex": 1.1647,
    "stockPrices": {
      "THYAO": 319.78,
      "EREGL": 50.6,
      "ASELS": 60.33,
      "GUBRF": 198.56,
      "KCHOL": 195.47,
      "TUPRS": 164.59,
      "YKBNK": 30.91,
      "BIMAS": 398.86,
      "SASA": 42.93,
      "ALTIN": 2486.14,
      "BTC": 67035.12,
      "ETH": 3739.84,
      "SOL": 170.09,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Emlak Balonu ve Yaren Leylek'in İtirazı",
      "body": "Yaren Leylek Bursa'daki yuvasına döndüğünde emlakçının fahiş kira talebiyle karşılaştı: 'Böyle fiyat olmaz, sıcak ülkelere geri döneceğim!' Konut Endeksi KFE fırladı."
    }
  },
  {
    "usdTry": 32.5629,
    "tcmbRate": 37,
    "kfeIndex": 1.168,
    "stockPrices": {
      "THYAO": 322.71,
      "EREGL": 50.15,
      "ASELS": 60.75,
      "GUBRF": 183.31,
      "KCHOL": 197.83,
      "TUPRS": 165.54,
      "YKBNK": 30.82,
      "BIMAS": 402.39,
      "SASA": 42.14,
      "ALTIN": 2506.24,
      "BTC": 67047.97,
      "ETH": 3761.1,
      "SOL": 166.41,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Küresel Pazar Resesyon Endişeleriyle Sallantıda",
      "body": "Demir-çelik talebindeki küresel yavaşlama nedeniyle EREGL tahtasında baskı sürüyor."
    }
  },
  {
    "usdTry": 32.6266,
    "tcmbRate": 37,
    "kfeIndex": 1.1713,
    "stockPrices": {
      "THYAO": 323.68,
      "EREGL": 49.63,
      "ASELS": 60.82,
      "GUBRF": 163.03,
      "KCHOL": 199.59,
      "TUPRS": 166.43,
      "YKBNK": 30.42,
      "BIMAS": 405.51,
      "SASA": 41.31,
      "ALTIN": 2524.24,
      "BTC": 66604.3,
      "ETH": 3715.09,
      "SOL": 159.48,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Şimşek'ten Londra Seferi",
      "body": "Hazine ve Maliye Bakanlığı yabancı fon yöneticileriyle masaya oturdu. Portföy girişlerinde kıpırdanma var, kur sakin."
    }
  },
  {
    "usdTry": 32.6886,
    "tcmbRate": 37,
    "kfeIndex": 1.1746,
    "stockPrices": {
      "THYAO": 322.61,
      "EREGL": 49.06,
      "ASELS": 60.54,
      "GUBRF": 142.37,
      "KCHOL": 200.69,
      "TUPRS": 167.26,
      "YKBNK": 29.79,
      "BIMAS": 408.17,
      "SASA": 40.48,
      "ALTIN": 2539.73,
      "BTC": 65797.82,
      "ETH": 3605.52,
      "SOL": 150.7,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "TÜİK Enflasyon Verilerini Açıkladı",
      "body": "TÜİK enflasyonun hissedilen kısmının aslında pürüzsüz olduğunu iddia etti. Vatandaş çarşı-pazarda hissedileni aramaya devam ediyor."
    }
  },
  {
    "usdTry": 32.749,
    "tcmbRate": 37,
    "kfeIndex": 1.178,
    "stockPrices": {
      "THYAO": 319.57,
      "EREGL": 48.47,
      "ASELS": 59.99,
      "GUBRF": 126.16,
      "KCHOL": 201.12,
      "TUPRS": 168.02,
      "YKBNK": 29.02,
      "BIMAS": 410.37,
      "SASA": 39.68,
      "ALTIN": 2552.6,
      "BTC": 64784.72,
      "ETH": 3443.42,
      "SOL": 141.97,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Kadıköy Kafelerinde 'Sandalye İşgaliye' Tartışması",
      "body": "Tek espresso alıp 6 saat ders çalışan müşterilerden rahatsız olan işletmeler, menülere 'boş bardak vergisi' eklemek istiyor."
    }
  },
  {
    "usdTry": 32.8075,
    "tcmbRate": 37,
    "kfeIndex": 1.1813,
    "stockPrices": {
      "THYAO": 314.72,
      "EREGL": 47.88,
      "ASELS": 59.24,
      "GUBRF": 118.14,
      "KCHOL": 200.9,
      "TUPRS": 168.71,
      "YKBNK": 28.23,
      "BIMAS": 412.07,
      "SASA": 38.97,
      "ALTIN": 2562.56,
      "BTC": 63738.68,
      "ETH": 3243.15,
      "SOL": 135,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Kriptocu Berbere Siber Denetim",
      "body": "Müşterilerine saç tıraşı yaparken kaldıraçlı altcoin işlemleri öneren mahalle berberi siber ekiplerce sözlü olarak uyarıldı."
    }
  },
  {
    "usdTry": 32.8643,
    "tcmbRate": 37,
    "kfeIndex": 1.1846,
    "stockPrices": {
      "THYAO": 308.32,
      "EREGL": 47.3,
      "ASELS": 58.38,
      "GUBRF": 120.21,
      "KCHOL": 200.08,
      "TUPRS": 169.32,
      "YKBNK": 27.52,
      "BIMAS": 413.28,
      "SASA": 38.37,
      "ALTIN": 2569.61,
      "BTC": 62849.89,
      "ETH": 3023.77,
      "SOL": 131.36,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "BIST Güzelleri Uçuşa Hazırlanıyor",
      "body": "Havacılık sektöründeki güçlü yolcu trafiği beklentisi THYAO tahtasını hareketlendirdi. Aracı kurumlar hedef fiyat yükseltiyor."
    }
  },
  {
    "usdTry": 32.9187,
    "tcmbRate": 37,
    "kfeIndex": 1.1879,
    "stockPrices": {
      "THYAO": 300.75,
      "EREGL": 46.76,
      "ASELS": 57.52,
      "GUBRF": 131.95,
      "KCHOL": 198.72,
      "TUPRS": 169.85,
      "YKBNK": 27.01,
      "BIMAS": 414.02,
      "SASA": 37.9,
      "ALTIN": 2573.54,
      "BTC": 62277.47,
      "ETH": 2804.56,
      "SOL": 131.85,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Mevduat Hesaplarında Stopaj Güncellemesi",
      "body": "Vadeli mevduat stopaj oranlarının artırılabileceği söylentisi mudiler arasında tartışmalara yol açtı."
    }
  },
  {
    "usdTry": 32.971,
    "tcmbRate": 37,
    "kfeIndex": 1.1912,
    "stockPrices": {
      "THYAO": 292.42,
      "EREGL": 46.28,
      "ASELS": 56.77,
      "GUBRF": 150.72,
      "KCHOL": 196.92,
      "TUPRS": 170.29,
      "YKBNK": 26.76,
      "BIMAS": 414.34,
      "SASA": 37.6,
      "ALTIN": 2574.49,
      "BTC": 62153.05,
      "ETH": 2606.24,
      "SOL": 136.71,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Gelir İdaresi'nden IBAN Operasyonu!",
      "body": "Maliye Bakanlığı kira gelirlerini 'elden aldım' veya 'açıklamaya bir şey yazma' diyerek elden/IBAN ile toplayan ev sahiplerini takibe aldı. Vergi denetimleri kapıda!"
    }
  },
  {
    "usdTry": 33.021,
    "tcmbRate": 37,
    "kfeIndex": 1.1945,
    "stockPrices": {
      "THYAO": 283.81,
      "EREGL": 45.86,
      "ASELS": 56.23,
      "GUBRF": 172.26,
      "KCHOL": 194.78,
      "TUPRS": 170.64,
      "YKBNK": 26.83,
      "BIMAS": 414.27,
      "SASA": 37.47,
      "ALTIN": 2572.42,
      "BTC": 62541.39,
      "ETH": 2446.42,
      "SOL": 145.25,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Ethereum Gaz Ücretleri Cüzdan Yaktı",
      "body": "Ağdaki NFT ve swap işlemlerinin artmasıyla işlem ücretleri (Gas fee) el yakmaya başladı."
    }
  },
  {
    "usdTry": 33.0691,
    "tcmbRate": 37,
    "kfeIndex": 1.1979,
    "stockPrices": {
      "THYAO": 275.41,
      "EREGL": 45.53,
      "ASELS": 55.98,
      "GUBRF": 191.72,
      "KCHOL": 192.45,
      "TUPRS": 170.9,
      "YKBNK": 27.23,
      "BIMAS": 413.89,
      "SASA": 37.52,
      "ALTIN": 2567.64,
      "BTC": 63454.06,
      "ETH": 2340.68,
      "SOL": 156.33,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Yapı Kredi Temettü Dağıtımı Açıkladı",
      "body": "YKBNK yönetim kurulu net kar payı dağıtma kararı aldığını duyurdu. Banka hisseleri endeksi yukarı taşıyor."
    }
  },
  {
    "usdTry": 33.1149,
    "tcmbRate": 37,
    "kfeIndex": 1.2012,
    "stockPrices": {
      "THYAO": 267.7,
      "EREGL": 45.31,
      "ASELS": 56.06,
      "GUBRF": 204.66,
      "KCHOL": 190.06,
      "TUPRS": 171.08,
      "YKBNK": 27.9,
      "BIMAS": 413.26,
      "SASA": 37.73,
      "ALTIN": 2560.24,
      "BTC": 64823.45,
      "ETH": 2298.19,
      "SOL": 168.18,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Kuyumcularda Çeyrek Altın Kuyruğu",
      "body": "Dolar kuru dalgalanırken vatandaşlar birikimlerini korumak için kuyumculara koştu. Çeyrek altın tedariğinde sıkıntı yaşanıyor."
    }
  },
  {
    "usdTry": 33.1588,
    "tcmbRate": 37,
    "kfeIndex": 1.2045,
    "stockPrices": {
      "THYAO": 261.11,
      "EREGL": 45.18,
      "ASELS": 56.51,
      "GUBRF": 208.2,
      "KCHOL": 187.75,
      "TUPRS": 171.17,
      "YKBNK": 28.78,
      "BIMAS": 412.46,
      "SASA": 38.08,
      "ALTIN": 2550.6,
      "BTC": 66534.05,
      "ETH": 2323.66,
      "SOL": 179.03,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Bitcoin 70 Bin Dolar Sınırında Pusu Kurdu",
      "body": "Fed'den gelen güvercin faiz açıklamalarıyla küresel risk iştahı arttı. Kriptocular saniyeleri sayıyor."
    }
  },
  {
    "usdTry": 33.2004,
    "tcmbRate": 37,
    "kfeIndex": 1.2078,
    "stockPrices": {
      "THYAO": 256.02,
      "EREGL": 45.18,
      "ASELS": 57.31,
      "GUBRF": 201.56,
      "KCHOL": 185.66,
      "TUPRS": 171.19,
      "YKBNK": 29.76,
      "BIMAS": 411.58,
      "SASA": 38.55,
      "ALTIN": 2538.91,
      "BTC": 68415.59,
      "ETH": 2414.2,
      "SOL": 187.11,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "BIST Hisselerinde Düzeltme Hareketi",
      "body": "Son haftalardaki hızlı yükseliş sonrası endekste kar realizasyonu başladı. Panik yapan küçük yatırımcı hisse satıyor."
    }
  },
  {
    "usdTry": 33.2403,
    "tcmbRate": 37,
    "kfeIndex": 1.2111,
    "stockPrices": {
      "THYAO": 252.7,
      "EREGL": 45.28,
      "ASELS": 58.41,
      "GUBRF": 186.32,
      "KCHOL": 183.91,
      "TUPRS": 171.13,
      "YKBNK": 30.74,
      "BIMAS": 410.72,
      "SASA": 39.11,
      "ALTIN": 2525.66,
      "BTC": 70289.28,
      "ETH": 2562.58,
      "SOL": 191.36,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Aselsan Yeni Savunma Anlaşması İmzaladı",
      "body": "Yerli hava savunma sistemi ihracatı için Ortadoğu ülkesiyle dev sözleşme imzalandı. Savunma hisselerinde yeşil mumlar uzuyor."
    }
  },
  {
    "usdTry": 33.2782,
    "tcmbRate": 37,
    "kfeIndex": 1.2145,
    "stockPrices": {
      "THYAO": 251.35,
      "EREGL": 45.5,
      "ASELS": 59.75,
      "GUBRF": 166.02,
      "KCHOL": 182.62,
      "TUPRS": 171,
      "YKBNK": 31.58,
      "BIMAS": 409.94,
      "SASA": 39.71,
      "ALTIN": 2511.15,
      "BTC": 71968.11,
      "ETH": 2755.06,
      "SOL": 191.2,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Küresel Pazar Resesyon Endişeleriyle Sallantıda",
      "body": "Demir-çelik talebindeki küresel yavaşlama nedeniyle EREGL tahtasında baskı sürüyor."
    }
  },
  {
    "usdTry": 33.3149,
    "tcmbRate": 37,
    "kfeIndex": 1.2178,
    "stockPrices": {
      "THYAO": 252.03,
      "EREGL": 45.83,
      "ASELS": 61.23,
      "GUBRF": 145.37,
      "KCHOL": 181.88,
      "TUPRS": 170.81,
      "YKBNK": 32.2,
      "BIMAS": 409.35,
      "SASA": 40.31,
      "ALTIN": 2495.98,
      "BTC": 73302.53,
      "ETH": 2975.28,
      "SOL": 187.01,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "BİM Mağazalarında İndirim İzdihamı",
      "body": "Ucuz mutfak aletleri kampanyası için sabah 07:00'de kuyruğa giren teyzeler kapıyı kırdı. BIMAS karları büyüyor."
    }
  },
  {
    "usdTry": 33.3501,
    "tcmbRate": 37,
    "kfeIndex": 1.2211,
    "stockPrices": {
      "THYAO": 254.69,
      "EREGL": 46.25,
      "ASELS": 62.76,
      "GUBRF": 129.16,
      "KCHOL": 181.76,
      "TUPRS": 170.57,
      "YKBNK": 32.54,
      "BIMAS": 409.02,
      "SASA": 40.87,
      "ALTIN": 2480.45,
      "BTC": 74176.08,
      "ETH": 3202.82,
      "SOL": 179.7,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "TÜİK Enflasyon Verilerini Açıkladı",
      "body": "TÜİK enflasyonun hissedilen kısmının aslında pürüzsüz olduğunu iddia etti. Vatandaş çarşı-pazarda hissedileni aramaya devam ediyor."
    }
  },
  {
    "usdTry": 33.3842,
    "tcmbRate": 37,
    "kfeIndex": 1.2244,
    "stockPrices": {
      "THYAO": 259.16,
      "EREGL": 46.76,
      "ASELS": 64.22,
      "GUBRF": 121.15,
      "KCHOL": 182.29,
      "TUPRS": 170.27,
      "YKBNK": 32.55,
      "BIMAS": 409.03,
      "SASA": 41.36,
      "ALTIN": 2465.12,
      "BTC": 74543.71,
      "ETH": 3417.85,
      "SOL": 170.88,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Bodrum Otellerinde Sezon Sonu Fiyat Kırılımı",
      "body": "Turizm sezonu kapanırken Bodrum Butik Otel fiyatlarında kış tarifesi başladı. Sektör geliri yavaşlıyor."
    }
  },
  {
    "usdTry": 33.4172,
    "tcmbRate": 37,
    "kfeIndex": 1.2277,
    "stockPrices": {
      "THYAO": 265.17,
      "EREGL": 47.33,
      "ASELS": 65.5,
      "GUBRF": 123.21,
      "KCHOL": 183.49,
      "TUPRS": 169.95,
      "YKBNK": 32.25,
      "BIMAS": 409.42,
      "SASA": 41.73,
      "ALTIN": 2450.33,
      "BTC": 74416.47,
      "ETH": 3600.43,
      "SOL": 162.25,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Kriptocu Berbere Siber Denetim",
      "body": "Müşterilerine saç tıraşı yaparken kaldıraçlı altcoin işlemleri öneren mahalle berberi siber ekiplerce sözlü olarak uyarıldı."
    }
  },
  {
    "usdTry": 33.4497,
    "tcmbRate": 37,
    "kfeIndex": 1.231,
    "stockPrices": {
      "THYAO": 272.36,
      "EREGL": 47.96,
      "ASELS": 66.53,
      "GUBRF": 134.95,
      "KCHOL": 185.33,
      "TUPRS": 169.59,
      "YKBNK": 31.69,
      "BIMAS": 410.25,
      "SASA": 41.96,
      "ALTIN": 2436.63,
      "BTC": 73883.16,
      "ETH": 3735.05,
      "SOL": 155.7,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Halka Arz Çılgınlığı: Çıtır Çerez Kuruyemiş Borsada!",
      "body": "Mahalle kuruyemişçisi CTRCZ koduyla halka açılıyor. Kişi başı 1.5 lot düştü, küçük yatırımcı tavan serisini bekliyor!"
    }
  },
  {
    "usdTry": 33.4817,
    "tcmbRate": 37,
    "kfeIndex": 1.2344,
    "stockPrices": {
      "THYAO": 280.3,
      "EREGL": 48.62,
      "ASELS": 67.24,
      "GUBRF": 153.71,
      "KCHOL": 187.77,
      "TUPRS": 169.22,
      "YKBNK": 30.95,
      "BIMAS": 411.56,
      "SASA": 42.03,
      "ALTIN": 2424.37,
      "BTC": 73075.42,
      "ETH": 3809.26,
      "SOL": 152.55,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Mevduat Hesaplarında Stopaj Güncellemesi",
      "body": "Vadeli mevduat stopaj oranlarının artırılabileceği söylentisi mudiler arasında tartışmalara yol açtı."
    }
  },
  {
    "usdTry": 33.5137,
    "tcmbRate": 37,
    "kfeIndex": 1.2377,
    "stockPrices": {
      "THYAO": 288.53,
      "EREGL": 49.29,
      "ASELS": 67.59,
      "GUBRF": 175.27,
      "KCHOL": 190.75,
      "TUPRS": 168.84,
      "YKBNK": 30.16,
      "BIMAS": 413.35,
      "SASA": 41.93,
      "ALTIN": 2414.04,
      "BTC": 72171.51,
      "ETH": 3817.28,
      "SOL": 153.72,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Zabıta Ekiplerinden Fahiş Fiyat Denetimi",
      "body": "Kadıköy kafelerine yapılan zabıta baskınlarında menüde fiyat yazmayan işletmelere ceza yağdı. İşletmeciler dertli."
    }
  },
  {
    "usdTry": 33.5457,
    "tcmbRate": 37,
    "kfeIndex": 1.241,
    "stockPrices": {
      "THYAO": 296.54,
      "EREGL": 49.95,
      "ASELS": 67.59,
      "GUBRF": 194.72,
      "KCHOL": 194.14,
      "TUPRS": 168.46,
      "YKBNK": 29.41,
      "BIMAS": 415.63,
      "SASA": 41.65,
      "ALTIN": 2405.85,
      "BTC": 71350.72,
      "ETH": 3757.86,
      "SOL": 159.14,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Ethereum Gaz Ücretleri Cüzdan Yaktı",
      "body": "Ağdaki NFT ve swap işlemlerinin artmasıyla işlem ücretleri (Gas fee) el yakmaya başladı."
    }
  },
  {
    "usdTry": 33.5782,
    "tcmbRate": 37,
    "kfeIndex": 1.2443,
    "stockPrices": {
      "THYAO": 303.87,
      "EREGL": 50.58,
      "ASELS": 67.25,
      "GUBRF": 207.67,
      "KCHOL": 197.85,
      "TUPRS": 168.11,
      "YKBNK": 28.82,
      "BIMAS": 418.39,
      "SASA": 41.21,
      "ALTIN": 2400.17,
      "BTC": 70793.46,
      "ETH": 3637.18,
      "SOL": 168.19,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Eurobond Kupon Ödemeleri Hesaba Geçti",
      "body": "Hazine dolar tahvili sahipleri kupon getirilerini alarak portföylerini tahkim etti. Dolar bazlı pasif gelir yüz güldürüyor."
    }
  },
  {
    "usdTry": 33.611,
    "tcmbRate": 37,
    "kfeIndex": 1.2476,
    "stockPrices": {
      "THYAO": 310.07,
      "EREGL": 51.17,
      "ASELS": 66.65,
      "GUBRF": 211.19,
      "KCHOL": 201.73,
      "TUPRS": 167.77,
      "YKBNK": 28.47,
      "BIMAS": 421.58,
      "SASA": 40.63,
      "ALTIN": 2397.16,
      "BTC": 70636.83,
      "ETH": 3465.79,
      "SOL": 179.44,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Kuyumcularda Çeyrek Altın Kuyruğu",
      "body": "Dolar kuru dalgalanırken vatandaşlar birikimlerini korumak için kuyumculara koştu. Çeyrek altın tedariğinde sıkıntı yaşanıyor."
    }
  },
  {
    "usdTry": 33.645,
    "tcmbRate": 37,
    "kfeIndex": 1.2509,
    "stockPrices": {
      "THYAO": 314.78,
      "EREGL": 51.69,
      "ASELS": 65.87,
      "GUBRF": 204.56,
      "KCHOL": 205.66,
      "TUPRS": 167.48,
      "YKBNK": 28.44,
      "BIMAS": 425.18,
      "SASA": 39.93,
      "ALTIN": 2397.1,
      "BTC": 70978.6,
      "ETH": 3260.28,
      "SOL": 191.26,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Yeni Yıl Öncesi Asgari Ücret Dedikoduları",
      "body": "Aralık ayı yaklaşırken asgari ücret tahminleri kurları ve enflasyon beklentilerini baskı altına aldı. TRY değer kaybediyor."
    }
  },
  {
    "usdTry": 33.6799,
    "tcmbRate": 37,
    "kfeIndex": 1.2543,
    "stockPrices": {
      "THYAO": 317.71,
      "EREGL": 52.12,
      "ASELS": 65,
      "GUBRF": 189.31,
      "KCHOL": 209.49,
      "TUPRS": 167.22,
      "YKBNK": 28.73,
      "BIMAS": 429.12,
      "SASA": 39.14,
      "ALTIN": 2400.03,
      "BTC": 71841.04,
      "ETH": 3038.97,
      "SOL": 201.77,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "BIST Hisselerinde Düzeltme Hareketi",
      "body": "Son haftalardaki hızlı yükseliş sonrası endekste kar realizasyonu başladı. Panik yapan küçük yatırımcı hisse satıyor."
    }
  },
  {
    "usdTry": 33.7164,
    "tcmbRate": 37,
    "kfeIndex": 1.2576,
    "stockPrices": {
      "THYAO": 318.68,
      "EREGL": 52.46,
      "ASELS": 64.16,
      "GUBRF": 169.02,
      "KCHOL": 213.07,
      "TUPRS": 167.02,
      "YKBNK": 29.32,
      "BIMAS": 433.33,
      "SASA": 38.31,
      "ALTIN": 2406.07,
      "BTC": 73189.04,
      "ETH": 2822.73,
      "SOL": 209.43,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "TCMB Para Politikası Kurulu: Faiz Oranı Sabit",
      "body": "Merkez Bankası faizleri sabit tutarak sıkı duruşun kararlılıkla sürdürüleceğini tekrarladı. Kur yatay."
    }
  },
  {
    "usdTry": 33.7542,
    "tcmbRate": 37,
    "kfeIndex": 1.2609,
    "stockPrices": {
      "THYAO": 317.61,
      "EREGL": 52.69,
      "ASELS": 63.44,
      "GUBRF": 148.38,
      "KCHOL": 216.3,
      "TUPRS": 166.88,
      "YKBNK": 30.14,
      "BIMAS": 437.74,
      "SASA": 37.48,
      "ALTIN": 2415.07,
      "BTC": 74913.64,
      "ETH": 2630.59,
      "SOL": 213.04,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Küresel Pazar Resesyon Endişeleriyle Sallantıda",
      "body": "Demir-çelik talebindeki küresel yavaşlama nedeniyle EREGL tahtasında baskı sürüyor."
    }
  },
  {
    "usdTry": 33.7938,
    "tcmbRate": 37,
    "kfeIndex": 1.2642,
    "stockPrices": {
      "THYAO": 314.57,
      "EREGL": 52.82,
      "ASELS": 62.96,
      "GUBRF": 132.16,
      "KCHOL": 219.06,
      "TUPRS": 166.81,
      "YKBNK": 31.1,
      "BIMAS": 442.25,
      "SASA": 36.68,
      "ALTIN": 2427.04,
      "BTC": 76869.29,
      "ETH": 2480.83,
      "SOL": 212.3,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Gübre Fabrikaları KAP Açıklaması",
      "body": "GUBRF altın sahası rezerv raporunun gecikeceğini duyurdu. Hissede taban serisi riski yatırımcıyı korkutuyor."
    }
  },
  {
    "usdTry": 33.8352,
    "tcmbRate": 37,
    "kfeIndex": 1.2675,
    "stockPrices": {
      "THYAO": 309.72,
      "EREGL": 52.83,
      "ASELS": 62.77,
      "GUBRF": 124.14,
      "KCHOL": 221.25,
      "TUPRS": 166.82,
      "YKBNK": 32.08,
      "BIMAS": 446.79,
      "SASA": 35.96,
      "ALTIN": 2441.74,
      "BTC": 78871.58,
      "ETH": 2386.74,
      "SOL": 207.53,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "TÜİK Enflasyon Verilerini Açıkladı",
      "body": "TÜİK enflasyonun hissedilen kısmının aslında pürüzsüz olduğunu iddia etti. Vatandaş çarşı-pazarda hissedileni aramaya devam ediyor."
    }
  },
  {
    "usdTry": 33.8787,
    "tcmbRate": 37,
    "kfeIndex": 1.2708,
    "stockPrices": {
      "THYAO": 303.32,
      "EREGL": 52.72,
      "ASELS": 62.92,
      "GUBRF": 126.21,
      "KCHOL": 222.82,
      "TUPRS": 166.9,
      "YKBNK": 32.99,
      "BIMAS": 451.25,
      "SASA": 35.36,
      "ALTIN": 2459.06,
      "BTC": 80741.61,
      "ETH": 2357.88,
      "SOL": 199.92,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Tarım Arazisine Isırılmış Döner Teklifi!",
      "body": "Sahip olduğunuz arazilere forumlar üzerinden yarısı ısırılmış döner ve 2005 model Tofaş Kartal takas teklifleri geliyor."
    }
  },
  {
    "usdTry": 33.9242,
    "tcmbRate": 37,
    "kfeIndex": 1.2742,
    "stockPrices": {
      "THYAO": 295.75,
      "EREGL": 52.51,
      "ASELS": 63.44,
      "GUBRF": 137.95,
      "KCHOL": 223.74,
      "TUPRS": 167.07,
      "YKBNK": 33.69,
      "BIMAS": 455.57,
      "SASA": 34.9,
      "ALTIN": 2478.64,
      "BTC": 82306.46,
      "ETH": 2396.48,
      "SOL": 190.98,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Kriptocu Berbere Siber Denetim",
      "body": "Müşterilerine saç tıraşı yaparken kaldıraçlı altcoin işlemleri öneren mahalle berberi siber ekiplerce sözlü olarak uyarıldı."
    }
  },
  {
    "usdTry": 33.972,
    "tcmbRate": 37,
    "kfeIndex": 1.2775,
    "stockPrices": {
      "THYAO": 287.42,
      "EREGL": 52.19,
      "ASELS": 64.3,
      "GUBRF": 156.72,
      "KCHOL": 223.99,
      "TUPRS": 167.32,
      "YKBNK": 34.13,
      "BIMAS": 459.65,
      "SASA": 34.6,
      "ALTIN": 2500.22,
      "BTC": 83443.1,
      "ETH": 2499.8,
      "SOL": 182.61,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Mevduat Faizlerinde Yarış Kızıştı",
      "body": "Özel bankalar yeni müşteri kazanmak için hoş geldin vadeli faizlerini %50'ye kadar çekti."
    }
  },
  {
    "usdTry": 34.0217,
    "tcmbRate": 37,
    "kfeIndex": 1.2808,
    "stockPrices": {
      "THYAO": 278.81,
      "EREGL": 51.79,
      "ASELS": 65.46,
      "GUBRF": 178.27,
      "KCHOL": 223.59,
      "TUPRS": 167.66,
      "YKBNK": 34.25,
      "BIMAS": 463.42,
      "SASA": 34.47,
      "ALTIN": 2523.32,
      "BTC": 84074.39,
      "ETH": 2658.01,
      "SOL": 176.44,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Mevduat Hesaplarında Stopaj Güncellemesi",
      "body": "Vadeli mevduat stopaj oranlarının artırılabileceği söylentisi mudiler arasında tartışmalara yol açtı."
    }
  },
  {
    "usdTry": 34.0737,
    "tcmbRate": 37,
    "kfeIndex": 1.2841,
    "stockPrices": {
      "THYAO": 270.41,
      "EREGL": 51.31,
      "ASELS": 66.84,
      "GUBRF": 197.72,
      "KCHOL": 222.6,
      "TUPRS": 168.09,
      "YKBNK": 34.05,
      "BIMAS": 466.81,
      "SASA": 34.52,
      "ALTIN": 2547.63,
      "BTC": 84201.35,
      "ETH": 2857.71,
      "SOL": 173.9,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Tüpraş Bakım Çalışmalarını Tamamladı",
      "body": "İzmit rafinerisinde planlı bakım bitti, üretim kapasitesi zirvede. TUPRS hisseleri güçlü."
    }
  },
  {
    "usdTry": 34.1278,
    "tcmbRate": 37,
    "kfeIndex": 1.2874,
    "stockPrices": {
      "THYAO": 262.7,
      "EREGL": 50.77,
      "ASELS": 68.34,
      "GUBRF": 210.66,
      "KCHOL": 221.1,
      "TUPRS": 168.6,
      "YKBNK": 33.57,
      "BIMAS": 469.78,
      "SASA": 34.73,
      "ALTIN": 2572.66,
      "BTC": 83881.41,
      "ETH": 3080.62,
      "SOL": 175.63,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Ethereum Gaz Ücretleri Cüzdan Yaktı",
      "body": "Ağdaki NFT ve swap işlemlerinin artmasıyla işlem ücretleri (Gas fee) el yakmaya başladı."
    }
  },
  {
    "usdTry": 34.1842,
    "tcmbRate": 37,
    "kfeIndex": 1.2907,
    "stockPrices": {
      "THYAO": 256.11,
      "EREGL": 50.2,
      "ASELS": 69.86,
      "GUBRF": 214.2,
      "KCHOL": 219.19,
      "TUPRS": 169.2,
      "YKBNK": 32.88,
      "BIMAS": 472.29,
      "SASA": 35.08,
      "ALTIN": 2598.07,
      "BTC": 83240.47,
      "ETH": 3307.51,
      "SOL": 181.66,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Bitcoin'de FOMO Çılgınlığı: Yeni Rekor!",
      "body": "Kripto piyasasında boğa koşusu hızlandı, yeni yatırımcılar borsalara akın ediyor. Kaldıraçlı işlem hacmi tavan."
    }
  },
  {
    "usdTry": 34.2425,
    "tcmbRate": 37,
    "kfeIndex": 1.2941,
    "stockPrices": {
      "THYAO": 251.02,
      "EREGL": 49.61,
      "ASELS": 71.29,
      "GUBRF": 207.56,
      "KCHOL": 216.99,
      "TUPRS": 169.88,
      "YKBNK": 32.09,
      "BIMAS": 474.32,
      "SASA": 35.55,
      "ALTIN": 2623.28,
      "BTC": 82435,
      "ETH": 3517.35,
      "SOL": 191.11,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Kuyumcularda Çeyrek Altın Kuyruğu",
      "body": "Dolar kuru dalgalanırken vatandaşlar birikimlerini korumak için kuyumculara koştu. Çeyrek altın tedariğinde sıkıntı yaşanıyor."
    }
  },
  {
    "usdTry": 34.3028,
    "tcmbRate": 37,
    "kfeIndex": 1.2974,
    "stockPrices": {
      "THYAO": 247.7,
      "EREGL": 49.02,
      "ASELS": 72.53,
      "GUBRF": 192.32,
      "KCHOL": 214.63,
      "TUPRS": 170.63,
      "YKBNK": 31.31,
      "BIMAS": 475.85,
      "SASA": 36.11,
      "ALTIN": 2647.92,
      "BTC": 81653.35,
      "ETH": 3691.9,
      "SOL": 202.61,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Emlak Vergilerinde Güncelleme",
      "body": "Lüks konut ve arsa sahipleri için vergi beyan sınırları yükseltildi. Gayrimenkul yatırımcıları yeni hesaplamalar yapıyor."
    }
  },
  {
    "usdTry": 34.3645,
    "tcmbRate": 37,
    "kfeIndex": 1.3007,
    "stockPrices": {
      "THYAO": 246.35,
      "EREGL": 48.45,
      "ASELS": 73.5,
      "GUBRF": 172.02,
      "KCHOL": 212.25,
      "TUPRS": 171.45,
      "YKBNK": 30.66,
      "BIMAS": 476.91,
      "SASA": 36.71,
      "ALTIN": 2671.44,
      "BTC": 81072.05,
      "ETH": 3814.96,
      "SOL": 214.31,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "BIST Hisselerinde Düzeltme Hareketi",
      "body": "Son haftalardaki hızlı yükseliş sonrası endekste kar realizasyonu başladı. Panik yapan küçük yatırımcı hisse satıyor."
    }
  },
  {
    "usdTry": 34.4279,
    "tcmbRate": 37,
    "kfeIndex": 1.304,
    "stockPrices": {
      "THYAO": 247.03,
      "EREGL": 47.93,
      "ASELS": 74.14,
      "GUBRF": 151.37,
      "KCHOL": 209.98,
      "TUPRS": 172.33,
      "YKBNK": 30.22,
      "BIMAS": 477.5,
      "SASA": 37.31,
      "ALTIN": 2693.55,
      "BTC": 80853.57,
      "ETH": 3876.4,
      "SOL": 224.51,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Türk Hava Yolları Yeni Uçaklar Satın Aldı",
      "body": "THYAO filosunu büyütmek için Airbus ile dev anlaşma imzaladı. Havacılık hisseleri hareketli."
    }
  },
  {
    "usdTry": 34.4927,
    "tcmbRate": 37,
    "kfeIndex": 1.3073,
    "stockPrices": {
      "THYAO": 249.69,
      "EREGL": 47.46,
      "ASELS": 74.42,
      "GUBRF": 135.15,
      "KCHOL": 207.98,
      "TUPRS": 173.27,
      "YKBNK": 30.08,
      "BIMAS": 477.69,
      "SASA": 37.87,
      "ALTIN": 2713.79,
      "BTC": 81103.58,
      "ETH": 3870.42,
      "SOL": 231.59,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Küresel Pazar Resesyon Endişeleriyle Sallantıda",
      "body": "Demir-çelik talebindeki küresel yavaşlama nedeniyle EREGL tahtasında baskı sürüyor."
    }
  },
  {
    "usdTry": 34.5588,
    "tcmbRate": 40,
    "kfeIndex": 1.3107,
    "stockPrices": {
      "THYAO": 254.16,
      "EREGL": 47.08,
      "ASELS": 74.34,
      "GUBRF": 127.14,
      "KCHOL": 206.35,
      "TUPRS": 174.26,
      "YKBNK": 30.26,
      "BIMAS": 477.51,
      "SASA": 38.36,
      "ALTIN": 2731.9,
      "BTC": 81876.24,
      "ETH": 3798.42,
      "SOL": 234.64,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "JPMorgan Raporu Sızdırıldı: Faiz Artış Beklentisi!",
      "body": "Uluslararası bankalardan sızan rapora göre TCMB politika faiz oranı %37 seviyesinden %40'a çıkabilir. Faiz getirisi pusu yolunda."
    }
  },
  {
    "usdTry": 34.6256,
    "tcmbRate": 40,
    "kfeIndex": 1.314,
    "stockPrices": {
      "THYAO": 260.17,
      "EREGL": 46.78,
      "ASELS": 73.95,
      "GUBRF": 129.21,
      "KCHOL": 205.21,
      "TUPRS": 175.28,
      "YKBNK": 30.76,
      "BIMAS": 477.03,
      "SASA": 38.73,
      "ALTIN": 2747.47,
      "BTC": 83147.33,
      "ETH": 3666.41,
      "SOL": 233.27,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "TÜİK Enflasyon Verilerini Açıkladı",
      "body": "TÜİK enflasyonun hissedilen kısmının aslında pürüzsüz olduğunu iddia etti. Vatandaş çarşı-pazarda hissedileni aramaya devam ediyor."
    }
  },
  {
    "usdTry": 34.6932,
    "tcmbRate": 40,
    "kfeIndex": 1.3173,
    "stockPrices": {
      "THYAO": 267.36,
      "EREGL": 46.59,
      "ASELS": 73.31,
      "GUBRF": 140.95,
      "KCHOL": 204.64,
      "TUPRS": 176.33,
      "YKBNK": 31.51,
      "BIMAS": 476.34,
      "SASA": 38.96,
      "ALTIN": 2760.35,
      "BTC": 84838.78,
      "ETH": 3487.12,
      "SOL": 228.06,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "BIST 100 Rekor Sonrası Devre Kesti!",
      "body": "Siyasi dedikodular ve tatil öncesi piknik parası çekmek isteyen balinaların satışıyla borsa çöktü. THYAO ve SASA tahtalarında işlemler geçici durduruldu."
    }
  },
  {
    "usdTry": 34.766,
    "tcmbRate": 40,
    "kfeIndex": 1.3208,
    "stockPrices": {
      "THYAO": 275.89,
      "EREGL": 46.5,
      "ASELS": 72.44,
      "GUBRF": 161.25,
      "KCHOL": 204.74,
      "TUPRS": 177.46,
      "YKBNK": 32.5,
      "BIMAS": 475.44,
      "SASA": 39.03,
      "ALTIN": 2770.83,
      "BTC": 86959.66,
      "ETH": 3260.85,
      "SOL": 219.47,
      "EUROBOND": 1000
    },
    "headline": {
      "title": "Kamu Müdahalesi: Varlık Fonu Borsaya Omuz Verdi!",
      "body": "Düşüşü gören kamu fonları borsaya taze likidite pompaladı. THYAO ve KCHOL tahtalarında yeşil mumlar uzadı."
    }
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TICKER_INFO, MACRO_DATABASE };
}
